## Домашнее задание 2
Изменение таблиц в Pandas  
Создайте датафрейм с клиентами:  
    clients = pd.DataFrame({  
    'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295, 939, 3840, 280, 20, 4332, 3475, 4213, 3113,  
                4809, 2134, 2242, 2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474],  
    'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060, 1189000207, 6821600300, 7137950720,  
                9510920050, 6131600255, 5428000070, 1788800910, 8100400160, 3123049142, 6306800010, 5083000375, 7920100025,  
                1951600150, 809001400, 339600110, 1622049154, 1099600250, 8563000110, 2768100205, 3995700435, 8861700030,  
                3303980210, 7731100066, 8146100580, 825069097, 3889100029, 9524100196]
    })  

house_id - это индексы датафрейма с домами

In [1]:
import pandas as pd
df = pd.read_csv('kc_house_data.csv', encoding= 'cp1251')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [2]:
clients = pd.DataFrame({
    'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295, 939, 3840,
                280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242, 2068, 4929, 1384, 1589, 3317,
                2260, 1727, 1764, 1611, 1474],
    'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060, 1189000207, 6821600300,
                    7137950720, 9510920050, 6131600255, 5428000070, 1788800910, 8100400160, 3123049142,
                    6306800010, 5083000375, 7920100025, 1951600150, 809001400, 339600110, 1622049154,
                    1099600250, 8563000110, 2768100205, 3995700435, 8861700030, 3303980210, 7731100066,
                    8146100580, 825069097, 3889100029, 952410019]
})

1. Присоедините к таблице clients данные по домам через метод join

In [3]:
clients_id = clients.set_index('house_id')
house_id = df.set_index('id')

In [4]:
clients_id.join(house_id)

,client_id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
house_id,,,,,,,,,,,,,,,,,,,,,
339600110,4809,20140923T000000,395000.0,3.0,2.50,1610.0,3755.0,2.0,0.0,0.0,...,7.0,1610.0,0.0,1987.0,0.0,98052.0,47.6825,-122.097,1300.0,3823.0
809001400,3113,20140922T000000,925000.0,3.0,1.00,1630.0,3200.0,1.5,0.0,0.0,...,8.0,1630.0,0.0,1912.0,0.0,98109.0,47.6351,-122.352,1710.0,3600.0
825069097,1764,20140619T000000,770000.0,3.0,2.50,2650.0,40705.0,2.0,0.0,0.0,...,9.0,2650.0,0.0,1994.0,0.0,98053.0,47.6680,-122.063,2550.0,42625.0
952410019,1474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1099600250,2242,20141202T000000,260000.0,3.0,1.75,1710.0,6400.0,1.0,0.0,0.0,...,7.0,1240.0,470.0,1976.0,0.0,98023.0,47.3036,-122.377,1600.0,6400.0
1189000207,2308,20141021T000000,387000.0,2.0,2.50,1170.0,1394.0,2.0,0.0,0.0,...,8.0,1170.0,0.0,2001.0,0.0,98122.0,47.6131,-122.297,1250.0,3136.0
1522700060,4535,20140624T000000,518000.0,4.0,2.75,2520.0,14021.0,2.0,0.0,0.0,...,9.0,2520.0,0.0,1999.0,0.0,98019.0,47.7344,-121.957,2330.0,14007.0
1622049154,2134,20141215T000000,289900.0,3.0,1.75,1899.0,11325.0,2.0,0.0,0.0,...,7.0,1899.0,0.0,1943.0,2005.0,98198.0,47.3987,-122.300,2000.0,10454.0
1788800910,939,20141020T000000,190000.0,3.0,1.00,1200.0,10458.0,1.0,0.0,0.0,...,6.0,1200.0,0.0,1961.0,0.0,98023.0,47.3262,-122.342,1160.0,9000.0
1951600150,4213,20150408T000000,180000.0,3.0,1.00,1610.0,8500.0,1.5,0.0,0.0,...,7.0,1610.0,0.0,1959.0,0.0,98032.0,47.3717,-122.297,1070.0,8750.0
2131701075,3942,20141204T000000,420000.0,3.0,1.75,1720.0,5000.0,1.5,0.0,0.0,...,8.0,1720.0,0.0,1932.0,2009.0,98019.0,47.7380,-121.983,1410.0,8300.0
2768100205,4929,20140625T000000,519000.0,4.0,2.50,1950.0,2617.0,1.5,0.0,0.0,...,7.0,1250.0,700.0,1910.0,0.0,98107.0,47.6696,-122.372,1520.0,1438.0
3123049142,280,20140805T000000,452000.0,3.0,2.25,2600.0,14810.0,1.0,0.0,2.0,...,8.0,1490.0,1110.0,1956.0,0.0,98166.0,47.4326,-122.341,2450.0,16715.0
3303980210,3317,20150427T000000,1115000.0,4.0,3.75,4040.0,14212.0,2.0,0.0,0.0,...,11.0,4040.0,0.0,2002.0,0.0,98059.0,47.5189,-122.147,3940.0,14212.0
3889100029,1611,20140617T000000,810000.0,3.0,2.50,2670.0,10481.0,2.0,0.0,0.0,...,9.0,2670.0,0.0,2003.0,0.0,98033.0,47.6673,-122.176,2620.0,8895.0
3995700435,1384,20140702T000000,265000.0,4.0,3.00,1940.0,8170.0,1.0,0.0,0.0,...,7.0,1940.0,0.0,1948.0,0.0,98155.0,47.7381,-122.302,1310.0,8169.0
5083000375,4332,20141027T000000,170000.0,3.0,1.00,1310.0,9529.0,1.0,0.0,0.0,...,7.0,1310.0,0.0,1956.0,0.0,98198.0,47.4105,-122.295,1330.0,9529.0
5083000375,4332,20150319T000000,235000.0,3.0,1.00,1310.0,9529.0,1.0,0.0,0.0,...,7.0,1310.0,0.0,1956.0,0.0,98198.0,47.4105,-122.295,1330.0,9529.0
5104540330,3498,20150508T000000,679000.0,4.0,2.50,3680.0,7236.0,2.0,0.0,0.0,...,10.0,3680.0,0.0,2006.0,0.0,98038.0,47.3543,-122.005,3310.0,7180.0
5428000070,2295,20150511T000000,770000.0,5.0,3.50,4750.0,8234.0,2.0,0.0,2.0,...,10.0,3350.0,1400.0,2013.0,0.0,98198.0,47.3574,-122.318,2160.0,14496.0
6131600255,4236,20141222T000000,202500.0,3.0,2.00,1540.0,8316.0,1.0,0.0,0.0,...,6.0,1540.0,0.0,1954.0,0.0,98002.0,47.3230,-122.216,1250.0,8316.0
6306800010,20,20140811T000000,436472.0,4.0,2.50,2692.0,8392.0,2.0,0.0,0.0,...,9.0,2692.0,0.0,2014.0,0.0,98030.0,47.3519,-122.197,2574.0,14446.0
6821600300,2866,20150318T000000,886000.0,3.0,2.25,2380.0,6000.0,2.0,0.0,0.0,...,9.0,1650.0,730.0,1931.0,0.0,98199.0,47.6472,-122.393,2000.0,6000.0
6823100225,4684,20150414T000000,700000.0,4.0,1.75,1870.0,6000.0,1.0,0.0,0.0,...,8.0,1670.0,200.0,1949.0,0.0,98199.0,47.6435,-122.399,1710.0,6000.0
7137950720,2765,20150304T000000,339100.0,4.0,2.50,2350.0,10655.0,2.0,0.0,0.0,...,8.0,2350.0,0.0,1992.0,0.0,98092.0,47.3284,-122.171,2210.0,7028.0
7731100066,2260,20140612T000000,545000.0,3.0,1.00,1510.0,5000.0,1.5,0.0,0.0,...,7.0,1510.0,0.0,1909.0,0.0,98105.0,47.6708,-122.297,1680.0,4000.0
7920100025,3475,20150427T000000,450000.0,2.0,1.00,740.0,5100.0,1.0,0.0,0.0,...,7.0,740.0,0.0,1947.0,0.0,98115.0,47.6787,-122.301,920.0,5100.0
8100400160,3840,20150413T000000,700000.0,3.0,2.25,2330.0,11424.0,2.0,0.0,0.0,...,8.0,2330.0,0.0,1984.0,0.0,98052.0,47.6386,-122.110,2050.0,11448.0
8146100580,1727,20141020T000000,765000.0,3.0,1.00,1220.0,7585.0,1.0,0.0,0.0,...,7.0,1220.0,0.0,1954.0,0.0,98004.0,47.6094,-122.194,1380.0,8918.0
8563000110,2068,20150424T000000,427000.0,4.0,1.75,1460.0,9750.0,1.0,0.0,0.0,...,7.0,1460.0,0.0,1967.0,0.0,98008.0,47.6205,-122.102,1820.0,9840.0
8861700030,1589,20141212T000000,510000.0,3.0,1.50,2400.0,10275.0,1.0,0.0,0.0,...,8.0,1540.0,860.0,1964.0,0.0,98052.0,47.6888,-122.126,2380.0,10125.0
8965450190,1459,20150218T000000,295000.0,3.0,2.50,1500.0,3060.0,2.0,0.0,0.0,...,7.0,1500.0,0.0,1994.0,0.0,98006.0,47.5605,-122.117,2700.0,7734.0
9510920050,1472,20140902T000000,725000.0,3.0,2.50,2980.0,16996.0,2.0,0.0,0.0,...,10.0,2980.0,0.0,1992.0,0.0,98075.0,47.5950,-122.016,2980.0,15438.0

2. Присоедините к таблице clients данные по домам через метод merge

In [ ]:
merged = clients.merge(df, left_on ='house_id', right_on = 'id', how = 'left')
merged